# Generated by Django 4.1.7 on 2023-04-01 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fullName",
            new_name="fullname",
        ),
    ]
